Doppler.Sap/Doppler.Sap.csproj, Doppler.Sap/public-keys/doppler_prod.xml, Doppler.Sap/public-keys/relay_prod.xml, Doppler.Sap/public-keys/relay_test.xml
Doppler.Sap should be used by Relay in production and test environments, also Doppler in Production and test too, so we need to add public keys to validate token in different environments
=> [DAT-133] Add doppler public keys

Doppler.Sap/Models/SapConfig.cs, Doppler.Sap/Services/DummyBillingService.cs, Doppler.Sap/Services/DummyBusinessPartnerService.cs, Doppler.Sap/Services/ServicesCollectionExtensions.cs, Doppler.Sap/Startup.cs, Doppler.Sap/appsettings.Development.json, Doppler.Sap/appsettings.int.json, Doppler.Sap/appsettings.qa.json
Dummy services for billing and business partner controllers were added to avoid VPN connection errors for qa and int environments
=> Add dummy data

Doppler.Sap.Test/Doppler.Sap.Test.csproj, Doppler.Sap.Test/IsSuAuthorizationPolicyTest.cs, Doppler.Sap.Test/WebApplicationFactoryHelper.cs, Doppler.Sap/DopplerSecurity/DopplerSecurityServiceCollectionExtensions.cs, Doppler.Sap/DopplerSecurity/IsSuperUserHandler.cs, Doppler.Sap/DopplerSecurity/IsSuperUserRequirement.cs
add handler to validate the issuu flag of the token in the sap api, along with its tests to validate when IsSU = true / False and when it is not sent.
🤚It is necessary to add the issu flag when the token is generated in doppler-job api so that the sap api does not fail in production
=> DAT-177-add-issu-permission

Doppler.Sap/Mappers/BusinessPartner/BusinessPartnerForArMapper.cs, Doppler.Sap/Mappers/BusinessPartner/BusinessPartnerForUsMapper.cs, Doppler.Sap/Models/DopplerUserDTO.cs
Change the types of the BillingStateId and StateId to string
**Changes:**
- Updated the type of the BillingStateId and StateId properties to string.
- Remove the dictionary to map the stateId Between Doppler and SAP. It functionallity will be add in Doppler's task: **DAT-209**.
**Task:** [DAT-210](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-210)
=> feat(BusinessPartner): Change the types of the BillingStateId and StateId to string

Doppler.Sap.Test/Mappers/BusinessPartnerForArMapperTest.cs, Doppler.Sap.Test/Mappers/BusinessPartnerForUsMapperTest.cs, Doppler.Sap/Factory/SapTaskHandler.cs, Doppler.Sap/Mappers/BusinessPartner/BusinessPartnerForArMapper.cs, Doppler.Sap/Mappers/BusinessPartner/BusinessPartnerForUsMapper.cs, Doppler.Sap/Mappers/BusinessPartner/BusinessPartnerMapper.cs, Doppler.Sap/Models/DopplerUserDTO.cs
Added logic to calculate the GroupCode depending if the SAP System is AR or US.
We need it implementation because in the databases the group code are different. For example:
AR:
US:
**Changes:**
- Added logic to calculate the GroupCode.
- Added new unit tests to verify the different scenarios of the GroupCode.
**Task:** [DAT-205](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-205)
=> feat: Add logic to calculate the GroupCode depending if use Ar or Us

Doppler.Sap/Mappers/BusinessPartner/BusinessPartnerForUsMapper.cs
We need to set `string.Empty` the state because Sap System returns an error if the state is null
=> Fix State of business partner mapper

Doppler.Sap.Test/BillingRequestHandlerTest.cs, Doppler.Sap.Test/BillingServiceTest.cs, Doppler.Sap.Test/Utils/DateTimeProviderTest.cs, Doppler.Sap/Doppler.Sap.csproj, Doppler.Sap/Mappers/Billing/BillingForArMapper.cs, Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs, Doppler.Sap/Models/SapConfig.cs, Doppler.Sap/Models/SapSaleOrderModel.cs, Doppler.Sap/Startup.cs, Doppler.Sap/Utils/DateTimeProvider.cs, Doppler.Sap/Utils/IDateTimeProvider.cs, Doppler.Sap/Utils/TimeZoneConfigurations.cs, Doppler.Sap/Utils/TimeZoneHelper.cs, Doppler.Sap/appsettings.json
Convert the UtcNow date to Argentina timezone for the dates in the invoice and payment.
**Changes:**
- Created a method in the class: ```DateTimeProvider``` to convert the UtcNow date to Argentina timezone.
- Added new UTs.
=> feat: Use Argentina timezone for the dates in the invoice and payment

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs, Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
The ```TransferReference``` property is not updated when the update the payment status.
**Task:** No task.
=> fix issue when the update the payment status

Doppler.Sap.Test/CreateOrUpdateBusinessPartnerHandlerTest.cs, Doppler.Sap/Factory/CreateOrUpdateBusinessPartnerHandler.cs
Add exception handle in CreateOrUpdateBusinessPartnerHandler to handle the exception "User can't have more than 10 accounts in Sap" for show the correct message in log and console.
=> feat: add exception handle in CreateOrUpdateBusinessPartnerHandler

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Remove the text `"+ TAX"` from Plan amount description, in the Billing US mapper.
Task: No Task.
=> [NO-TICKET] - Fix plan amount description

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Remove the text "+ TAX" from item description, in the Billing US mapper.
Task: No Task.
=> [NO-TICKET] - Fix billing item description

Doppler.Sap.Test/BusinessPartnerServiceTest.cs, Doppler.Sap.Test/Controllers/BusinessPartnerControllerTest.cs, Doppler.Sap/Validations/BusinessPartner/BusinessPartnerForArValidation.cs, Doppler.Sap/Validations/BusinessPartner/BusinessPartnerForUsValidation.cs
Add a new validation when the system try to creates or updates some business partner and this doesn't have first name and last name.
Now when the business partner has ```FirstName == ''```  and ```LastName == ''```, the endpoint throws an exception.
**Changes:**
- Add new validation.
- Add new unit tests.
**Task:** [DAT-253](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-253)
=> feat: Add validation about first name and last name when create or update some business partner

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Updated the free text for the Email surplus.
**Before:** Excess emails 2364 - $0.0003  - Period 01 2021
**Now:** Email surplus: 2364. - $0,0003 - Period 01 2021
**Task:** [DAT-262](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-262)
=> feat: Update free text for the Email surplus

Doppler.Sap.Test/BillingServiceTest.cs, Doppler.Sap.Test/Controllers/BillingControllerTest.cs, Doppler.Sap.Test/CreditNoteHandlerTest.cs, Doppler.Sap/Controllers/BillingController.cs, Doppler.Sap/Enums/CreditNoteEnum.cs, Doppler.Sap/Enums/SapTaskEnum.cs, Doppler.Sap/Factory/CreditNoteHandler.cs, Doppler.Sap/Factory/SapTaskFactory.cs, Doppler.Sap/Mappers/Billing/BillingForArMapper.cs, Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs, Doppler.Sap/Mappers/Billing/IBillingMapper.cs, Doppler.Sap/Models/BillingConfig.cs, Doppler.Sap/Models/CreditNoteRequest.cs, Doppler.Sap/Models/SapCreditNoteDocumentLineModel.cs, Doppler.Sap/Models/SapCreditNoteModel.cs, Doppler.Sap/Models/SapDocumentLineResponse.cs, Doppler.Sap/Models/SapTask.cs, Doppler.Sap/Services/BillingService.cs, Doppler.Sap/Services/DummyBillingService.cs, Doppler.Sap/Services/IBillingService.cs, Doppler.Sap/Startup.cs, Doppler.Sap/Validations/Billing/BillingForArValidation.cs, Doppler.Sap/Validations/Billing/BillingForUsValidation.cs, Doppler.Sap/Validations/Billing/IBillingValidation.cs, Doppler.Sap/appsettings.json
Allow to create a credit note with no refund  in SAP.
**Changes:**
- Added new endpoint to create a credit note in SAP.
- Add new UTs.
**Task:** [DAT-266](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-266)
=> feat: send credit notes with no refund to SAP

Doppler.Sap.Test/BillingServiceTest.cs, Doppler.Sap/Mappers/Billing/BillingForArMapper.cs, Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
We need to change the description to remove unnecessary text for Individual Doppler clients
Examples:
Individual
Monthly
=> Fix: [DAT-292] Fix invoice detail for Individual clients of Doppler

Doppler.Sap.Test/CreditNoteHandlerTest.cs, Doppler.Sap/Mappers/Billing/BillingForArMapper.cs, Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs, Doppler.Sap/Models/CreditNoteRequest.cs, Doppler.Sap/Models/SapCreditNoteDocumentLineModel.cs
When an admin creates a new note credit without refund, We need to add a reason, so for this property in CreateCreditNote endpoint
=> [DAT-279]  Create a Credit note without refund - Add Reason selector 

Doppler.Sap.Test/Mappers/BusinessPartnerForArMapperTest.cs, Doppler.Sap.Test/Mappers/BusinessPartnerForUsMapperTest.cs, Doppler.Sap/Mappers/BusinessPartner/BusinessPartnerForArMapper.cs, Doppler.Sap/Mappers/BusinessPartner/BusinessPartnerForUsMapper.cs, Doppler.Sap/Mappers/BusinessPartner/BusinessPartnerMapper.cs
Rename contactId when the client has repeated contact id in the contacts because SAP throws an exception when the Business Partner has the same contact's name for two or more contacts.
Before:
``` ContactEmployees = new List<SapContactEmployee>
{
new SapContactEmployee
{
Name = "test",
E_Mail = "test@hotmail.com),
CardCode = "xxx",
Active = "tYES",
EmailGroupCode = 'Billing"
},
new SapContactEmployee
{
Name = "test",
E_Mail = "test@gmail.com),
CardCode = "xxx",
Active = "tYES",
EmailGroupCode = 'Billing"
}
};
```
After:
``` ContactEmployees = new List<SapContactEmployee>
{
new SapContactEmployee
{
Name = "test1",
E_Mail = "test@hotmail.com),
CardCode = "xxx",
Active = "tYES",
EmailGroupCode = 'Billing"
},
new SapContactEmployee
{
Name = "test2",
E_Mail = "test@gmail.com),
CardCode = …
```
=> [DAT-273] - Rename contactId when the client has 2 o more repeated id in the contacts

Doppler.Sap.Test/Mappers/BusinessPartnerForArMapperTest.cs, Doppler.Sap/Enums/FiscalTypeEnum.cs, Doppler.Sap/Mappers/BusinessPartner/BusinessPartnerForArMapper.cs
Calculate the correct ```FiscalType``` given a ```idConsumerType and federalTaxId```. It change applies only for the SAP AR.
**Bug:** [DAT-326](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-326)
=> [DAT-326] - calculate the fiscal type given a consumer type and federal tax id

build-n-publish.sh
Replaces the version number in version.txt with the full canonical image name.
The idea is to apply the same approach in other repositories too.
=> chore: include image name in version.txt

Jenkinsfile
Fix Jenkingsfile in order to fix some problems with the deployment, changing `readCurrentTag()` function:
```
def String readCurrentTag() {
return sh(returnStdout: true, script: 'echo ${TAG_NAME}').trim()
}
```
=> [NO-TICKET] - Fix Jenkinsfile
