FromDoppler/doppler-sap

.dependabot/config.yml

Add config.yml to dependabot feature
https://app.dependabot.com/

[DAT-130] Add dependabot config

---

.gitignore
Doppler.Sap.Test/BillingServiceTest.cs
Doppler.Sap.Test/Controllers/BillingControllerTest.cs
Doppler.Sap.Test/SetCurrencyRateHandlerTest.cs
Doppler.Sap.Test/TaskRepeaterTest.cs
Doppler.Sap/Controllers/BillingController.cs
Doppler.Sap/Enums/SapTaskEnum.cs
Doppler.Sap/Factory/ISapTaskFactory.cs
Doppler.Sap/Factory/SapTaskFactory.cs
Doppler.Sap/Factory/SapTaskHandler.cs
Doppler.Sap/Factory/SetCurrencyRateHandler.cs
Doppler.Sap/Mappers/CurrencyRateMapper.cs
Doppler.Sap/Models/CurrencyRateDto.cs
Doppler.Sap/Models/SapConfig.cs
Doppler.Sap/Models/SapCurrencyRate.cs
Doppler.Sap/Models/SapLoginCookies.cs
Doppler.Sap/Models/SapTask.cs
Doppler.Sap/Models/SapTaskResult.cs
Doppler.Sap/Program.cs
Doppler.Sap/Services/BillingService.cs
Doppler.Sap/Services/IBillingService.cs
Doppler.Sap/Services/IQueuingService.cs
Doppler.Sap/Services/ISapService.cs
Doppler.Sap/Services/QueuingService.cs
Doppler.Sap/Services/SapService.cs
Doppler.Sap/Startup.cs
Doppler.Sap/TaskRepeater.cs
Doppler.Sap/Utils/DateTimeProvider.cs
Doppler.Sap/Utils/IDateTimeProvider.cs
Doppler.Sap/appsettings.json

Add BillingController->SetCurrencyRate endopoint

[DAT-125] - Add SetCurrencyRate endpoint in Billing controller

---

Doppler.Sap.Test/BillingRequestHandlerTest.cs
Doppler.Sap.Test/SapTaskHandlerTest.cs
Doppler.Sap/Factory/SapTaskHandler.cs
Doppler.Sap/Models/SapConfig.cs
Doppler.Sap/Models/SapLoginCookies.cs
Doppler.Sap/appsettings.json

We need to check cookies session on the Sap system to use the services, currently, we use 30 minutes to expire the session
see example
Can you review it?

[DAT-133] Add cookies session control for Sap login

---

Doppler.Sap/Controllers/TestSapController.cs
Doppler.Sap/Services/ITestSapService.cs
Doppler.Sap/Services/TestSapService.cs
Doppler.Sap/Startup.cs

We need check if can connect with Sap inside of Swarm network

[DAT-162] Add SapTest endpoint

---

Doppler.Sap/Program.cs
Doppler.Sap/appsettings.Development.json
Doppler.Sap/appsettings.int.json
Doppler.Sap/appsettings.json
Doppler.Sap/appsettings.qa.json

accept docker windows configuration files for local debug. this chage was requested by @andresmoschini, @nreal can you check it please?

Local debug improvement

---

Doppler.Sap.Test/Doppler.Sap.Test.csproj
Doppler.Sap.Test/IsSuAuthorizationPolicyTest.cs
Doppler.Sap/DopplerSecurity/DopplerSecurityServiceCollectionExtensions.cs
Doppler.Sap/DopplerSecurity/IsSuperUserHandler.cs
Doppler.Sap/DopplerSecurity/IsSuperUserRequirement.cs

the issu permission was added to the default authorization policy along with its test that performs the tests by sending the tag with the true/false values ​​and without sending it in the token.

Dat 177 add is su permission

---

Doppler.Sap.Test/BillingRequestHandlerTest.cs
Doppler.Sap.Test/BusinessPartnerServiceTest.cs
Doppler.Sap.Test/CreateOrUpdateBusinessPartnerHandlerTest.cs
Doppler.Sap.Test/IsSuAuthorizationPolicyTest.cs
Doppler.Sap.Test/SetCurrencyRateHandlerTest.cs
Doppler.Sap/Enums/ResponsabileBillingEnum.cs
Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Factory/CreateOrUpdateBusinessPartnerHandler.cs
Doppler.Sap/Factory/ISapServiceSettingsFactory.cs
Doppler.Sap/Factory/ISapTaskHandler.cs
Doppler.Sap/Factory/SapServiceSettingsFactory.cs
Doppler.Sap/Factory/SapTaskHandler.cs
Doppler.Sap/Factory/SetCurrencyRateHandler.cs
Doppler.Sap/Models/DopplerUserDTO.cs
Doppler.Sap/Models/SapConfig.cs
Doppler.Sap/Services/BusinessPartnerService.cs
Doppler.Sap/Utils/SapServiceSettings.cs
Doppler.Sap/Utils/SapSystemHelper.cs
Doppler.Sap/appsettings.Development.json
Doppler.Sap/appsettings.json

Changed the logic to get the SAP's system. Now the SAP's system is determined by ```Billing System``` instead of ```Country Code```.
**Changes:**
- Changed the logic to determined the SAP's system.
- Updated unit tests.
**Task:** [DAT-208](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-208)

feat(sap_us): Change logic to get the sap's system

---

Doppler.Sap/Factory/CreateOrUpdateBusinessPartnerHandler.cs
Doppler.Sap/Mappers/BusinessPartner/BusinessPartnerForUsMapper.cs

We fix a problem when sends a Business partner from Relay with US country, Sap service uses the database of the AR, now Sap services uses US database

fix: fix business partner us

---

Doppler.Sap.Test/BillingRequestHandlerTest.cs
Doppler.Sap.Test/BillingServiceTest.cs
Doppler.Sap.Test/BusinessPartnerServiceTest.cs
Doppler.Sap.Test/CreateOrUpdateBusinessPartnerHandlerTest.cs
Doppler.Sap/Extensions/SapBillingItemsServiceCollectionExtension.cs
Doppler.Sap/Extensions/SapMappersServiceCollectionExtension.cs
Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Factory/CreateOrUpdateBusinessPartnerHandler.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Mappers/Billing/IBillingMapper.cs
Doppler.Sap/Models/BillingConfig.cs
Doppler.Sap/Models/BillingRequest.cs
Doppler.Sap/Models/SapBusinessPartner.cs
Doppler.Sap/Models/SapDocumentLineModel.cs
Doppler.Sap/Models/SapSaleOrderModel.cs
Doppler.Sap/Models/SapServiceConfig.cs
Doppler.Sap/Services/BillingService.cs
Doppler.Sap/Services/BusinessPartnerService.cs
Doppler.Sap/Services/ISapBillingItemsService.cs
Doppler.Sap/Services/SapBillingItemsService.cs
Doppler.Sap/Startup.cs
Doppler.Sap/Validations/Billing/BillingForArValidation.cs
Doppler.Sap/Validations/Billing/BillingForUsValidation.cs
Doppler.Sap/Validations/Billing/IBillingValidation.cs
Doppler.Sap/Validations/BusinessPartner/BusinessPartnerForArValidation.cs
Doppler.Sap/Validations/BusinessPartner/BusinessPartnerForUsValidation.cs
Doppler.Sap/Validations/BusinessPartner/IBusinessPartnerValidation.cs
Doppler.Sap/appsettings.json

Create invoices in SAP when the billing country of the business partner is US.
**Changes:**
- Added functionality to create invoices in SAP when the billing country of the business partner is US.
- Added new UTs.
**Task:** [DAT-190](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-190)

feat(sap_us): Integrate invoices with SAP US

---

Doppler.Sap.Test/BillingRequestHandlerTest.cs
Doppler.Sap.Test/BillingServiceTest.cs
Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Mappers/Billing/IBillingMapper.cs
Doppler.Sap/Models/BillingConfig.cs
Doppler.Sap/Models/BillingRequest.cs
Doppler.Sap/Models/SapIncomingPaymentModel.cs
Doppler.Sap/Models/SapPaymentInvoiceModel.cs
Doppler.Sap/Models/SapSaleOrderInvoiceResponse.cs
Doppler.Sap/Models/SapSaleOrderModel.cs
Doppler.Sap/appsettings.json

Send the Incoming Payment to SAP.
The payments only can be send to SAP if the "NeedCreateIncomingPayments" setting is true and the payment from FirstData is approved. 
**Task:** [DAT-202](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-202)

Feat: send payment to SAP

---

Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Mappers/Billing/IBillingMapper.cs
Doppler.Sap/Models/BillingRequest.cs
Doppler.Sap/Models/SapSaleOrderModel.cs

Send the ```transfer reference``` to sap when the payment is created. The ```transfer reference``` contains the ```Authorization Number``` from FirstData.
**Task:** [DAT-231](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-231)

feat: send the transfer reference to sap with the Authorization number from FirstData

---

Doppler.Sap/Services/SapBillingItemsService.cs

fix issue when the plan is custom. I added a check for the ```HasValue``` property.
**Task:** No task.

fix issue for the custom plan

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

fix an issue when the surplus emails is null. I added a check for the HasValue property.
Task: No task.

Fix issue for the surplus emails

---

Doppler.Sap.Test/BillingRequestHandlerTest.cs
Doppler.Sap.Test/BillingServiceTest.cs
Doppler.Sap.Test/Controllers/BillingControllerTest.cs
Doppler.Sap/Controllers/BillingController.cs
Doppler.Sap/Enums/SapTaskEnum.cs
Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Factory/ISapTaskHandler.cs
Doppler.Sap/Factory/SapTaskFactory.cs
Doppler.Sap/Factory/SapTaskHandler.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Mappers/Billing/IBillingMapper.cs
Doppler.Sap/Models/BillingRequest.cs
Doppler.Sap/Models/SapInvoiceList.cs
Doppler.Sap/Models/SapSaleOrderModel.cs
Doppler.Sap/Models/UpdatePaymentStatusRequest.cs
Doppler.Sap/Services/BillingService.cs
Doppler.Sap/Services/DummyBillingService.cs
Doppler.Sap/Services/IBillingService.cs
Doppler.Sap/Validations/Billing/BillingForArValidation.cs
Doppler.Sap/Validations/Billing/BillingForUsValidation.cs
Doppler.Sap/Validations/Billing/IBillingValidation.cs

Add new endpoint to update the invoices in SAP. The funcionality of the enpoint is update the invoice in SAP and also create the ```IncomingPayment``` in SAP is the ```TransactionApproval``` is true
**Changes:**
- Add new endpoint in the BillingController.
- Add new unit tests.
**Task:** [DAT-237](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-237)

feat: Add "UpdateBilling" endpoint

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Models/SapIncomingPaymentModel.cs

I included a new property (```U_ClaseCashfloCaja```) in the payment request and I changed the accounting account when we send the IncomingPayment to SAP.
**Task:** [DAT-239](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-239)

feat: include new property in the payment and change the accounting account

---

Doppler.Sap/appsettings.json

Update the config to use the SAP PROD

feat: update prod config

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs

Add check if the ```SurplusEmails``` has value in the AR mapper.
**Task:** No Task.

fix issue with extra email

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Change the value for the CostingCode4.
**Now:**
NOAPLI4
**Before:**
NOAPL4
**Task:** No task

fix issue with code costing 4 in sap

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Translate the value of the ```JournalRemarks``` property to english.
**Before:**
```Pagos recibidos - {cardCode}```
**Now:**
```Incoming Payments - {cardCode}```
**Task:** [DAT-246](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-246)

feat: Translate the value of the "JournalRemarks" property to english.

---

Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Add the InvoiceId in the Billing mappers for the AR and US.
**Task:** No task

fix: Map InvoiceId in the Billing mappers (AR/US)

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Models/BillingRequest.cs

Add the DiscountedAmount property in the SAP service. It property is used when the invoice is generating from excel file form the Admin.
**Task:** No task

feat: add DiscountedAmount property

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Remove the invoice line when the amount is 0.

feat: remove the invoice line when the amount is 0

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Update the periodicities's text.
**Before:**
```
{0, "Monthly"},
{1, "Quarterly"},
{2, "Biannual"},
{3, "Annual"}
```
**Now:**
```
{0, "Period Monthly"},
{1, "Period Pay 3 months"},
{2, "Period Pay 6 months"},
{3, "Period Pay 12 months"}
```
**Task:** [DAT-263](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-263)

feat: update the periodicities's text

---

Doppler.Sap/Services/SapBillingItemsService.cs

Return custom plan when not exits then item code

feat: return custom plan when not exits then item code

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Replace 'Payment' by 'Period' and also update periodicity label
**Task:** No task

feat: replace 'Payment' by 'Period' and also update periodicity label

---

Doppler.Sap.Test/BillingServiceTest.cs
Doppler.Sap.Test/Controllers/BillingControllerTest.cs
Doppler.Sap.Test/CreditNoteHandlerTest.cs
Doppler.Sap/Controllers/BillingController.cs
Doppler.Sap/Enums/SapTaskEnum.cs
Doppler.Sap/Factory/CreditNoteHandler.cs
Doppler.Sap/Factory/ISapTaskHandler.cs
Doppler.Sap/Factory/SapTaskFactory.cs
Doppler.Sap/Factory/SapTaskHandler.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Mappers/Billing/IBillingMapper.cs
Doppler.Sap/Models/BillingConfig.cs
Doppler.Sap/Models/CancelCreditNoteRequest.cs
Doppler.Sap/Models/SapCreditNoteDocumentLineModel.cs
Doppler.Sap/Models/SapCreditNoteList.cs
Doppler.Sap/Models/SapCreditNoteModel.cs
Doppler.Sap/Models/SapCreditNoteResponse.cs
Doppler.Sap/Models/SapOutgoingPaymentLineModel.cs
Doppler.Sap/Models/SapOutgoingPaymentModel.cs
Doppler.Sap/Models/SapTask.cs
Doppler.Sap/Models/UpdateCreditNotePaymentStatusRequest.cs
Doppler.Sap/Services/BillingService.cs
Doppler.Sap/Services/DummyBillingService.cs
Doppler.Sap/Services/IBillingService.cs
Doppler.Sap/Validations/Billing/BillingForArValidation.cs
Doppler.Sap/Validations/Billing/BillingForUsValidation.cs
Doppler.Sap/Validations/Billing/IBillingValidation.cs
Doppler.Sap/appsettings.json

Ability to create/update or cancel a credit note with refund in SAP (AR/US).
**Changes:**
- Update the **CreateCreditNote endpoint** to support credit note with refund.
- Create an **endpoint to update** the credit note.
- Create an **endpoint to cancel** the credit note.
- Add new UTs.
**Task:** [DAT-267](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-267)

feat: send credit note with refund to SAP

---

Doppler.Sap.Test/BillingServiceTest.cs
Doppler.Sap/Controllers/BillingController.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Mappers/Billing/IBillingMapper.cs
Doppler.Sap/Models/InvoiceResponse.cs
Doppler.Sap/Services/BillingService.cs
Doppler.Sap/Services/DummyBillingService.cs
Doppler.Sap/Services/IBillingService.cs

Create new a endpoint to get an invoice from SAP given a dopplerInvoiceId.
**Changes:**
- Create a new endpoint.
- Add new UTs.
**Task:** [DAT-297](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-297)

feat: add endpoint to get an invoice from SAP given a dopplerInvoiceId

---

Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Factory/CreditNoteHandler.cs

In this PR we only fix the text that is logging when there is an error.

[NO_TICKET] - Fix error logging

---

Doppler.Sap.Test/BillingRequestHandlerTest.cs
Doppler.Sap.Test/Utils/HttpHelperExtension.cs
Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Mappers/Billing/IBillingMapper.cs

The payment date is the creat invoice date, now with this fix, the payment date is DateTime.Now because when executing this process the payment is created
Ticket [DAT-301](https://makingsense.atlassian.net/browse/DAT-301)

[DAT-301] Payments - Fix payment date

---

Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Models/SapTaskResult.cs
Doppler.Sap/TaskRepeater.cs

When a payment was creating, there were a exception because the field U_DPL_INV_ID was null, when invoice came from MVC (Buy credits or buy monthly plan not recurrent). 
That was because the field U_DPL_INV_ID had value 0, so was sending null to SAP. 
Now, id the value is 0, is sending to SAP too.

[NO-TICKET] - Fix creating payment

---

Dockerfile
Doppler.Sap.Test/Doppler.Sap.Test.csproj
Doppler.Sap/Doppler.Sap.csproj

Update project to .net 5 and dependencies

Update dot net5

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

fix issue when try to update an invoice in SAP. The problem was that the property ```U_DPL_INV_ID```  was not set.

fix issue when update invoice in SAP

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Models/SapDocumentLineModel.cs

Update dimensions for SAP AR/US
**Task:** [DAT-330](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-330)

[DAT-330] - Update dimensions for SAP AR/US

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Remove the "DiscountPercent" property when creates a new credit note in SAP

{No-Ticket] - Remove DiscountPercent for credit note

---

Doppler.Sap/Factory/CreateOrUpdateBusinessPartnerHandler.cs
Doppler.Sap/Models/SapBusinessPartner.cs

We need to send a new property ("property15") equal "Y" to SAP  when the BP is created
**Task:** [DAT-359](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-359)

[DAT-358] - send new property to SAP when the BP is created

---

Doppler.Sap.Test/BusinessPartnerServiceTest.cs
Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Factory/CreditNoteHandler.cs
Doppler.Sap/Factory/SapServiceSettingsFactory.cs
Doppler.Sap/Services/BillingService.cs
Doppler.Sap/Services/BusinessPartnerService.cs
Doppler.Sap/Utils/SapServiceSettings.cs

Add more information for slack notifications

[DAT-325] Fix slack notification

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs

Update mapper for the billing to support create the sale orders when the payment method is "MercadoPago" from the Admin
**Task:** [DAT-251](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-251)

feat: update mapper for the billing of the SAP AR

---

Doppler.Sap.Test/BillingRequestHandlerTest.cs
Doppler.Sap.Test/BillingServiceTest.cs
Doppler.Sap.Test/CreditNoteHandlerTest.cs
Doppler.Sap/Controllers/BillingController.cs
Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Factory/CreditNoteHandler.cs
Doppler.Sap/Factory/ISapTaskHandler.cs
Doppler.Sap/Factory/SapTaskHandler.cs
Doppler.Sap/Services/BillingService.cs
Doppler.Sap/Services/DummyBillingService.cs
Doppler.Sap/Services/IBillingService.cs

Change logic to support send InvoiceId to SAP from Relay
**Task:** [DAT-397](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-397)

[DAT-397] Change logic to support send InvoiceId to SAP from Relay

---

Doppler.Sap/Factory/BillingRequestHandler.cs

Change logic to calculate origin when the invoice is created in SAP
**Task:** No ticket

[No-Ticket] - Change logic to calculate origin when the invoice is created in SAP

---

Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Mappers/Billing/IBillingMapper.cs
Doppler.Sap/Models/BillingRequest.cs
Doppler.Sap/Models/SapSaleOrderModel.cs
Doppler.Sap/Models/UpdatePaymentStatusRequest.cs

Add two new properties ```InvoiceDate``` and ```PaymentDate``` in the CreateInvoice and UpdateInvoice endpoints.
These properties are used to set the dates in the invoices and payments when it send to SAP.
**Task:** [DAT-411](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-411)

DAT-411 - Add InvoiceDate and PaymentDate properties

---

Doppler.Sap.Test/BillingRequestHandlerTest.cs
Doppler.Sap.Test/TaskRepeaterTest.cs
Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/TaskRepeater.cs

send slack notification from taskrepeater

feat: send slack notification from taskrepeater

---

Doppler.Sap/Factory/SapTaskHandler.cs

fix issue when the FiscalId is null in SAP

fix issue when the FiscalId is null in SAP

---

Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Factory/CreateOrUpdateBusinessPartnerHandler.cs
Doppler.Sap/Factory/CreditNoteHandler.cs

This PR add User id to the slack notification, in order to know which user is having an error.

[DAT-475] - Add user id to slack alert

---

Doppler.Sap.Test/IsSuAuthorizationPolicyTest.cs

[NO-TICKET] - Fix unit test

---

Doppler.Sap/Factory/BillingRequestHandler.cs
Doppler.Sap/Factory/CreditNoteHandler.cs

Add ClientId or CardCode to Slack alerts in the cases that didnt have.

[DAT-508] - Add information to slack alert

---

Doppler.Sap/Factory/SapTaskHandler.cs

Filtrar los BPs inactivos cuando se hace un get desde SAP.
**Task:** [DAT-518](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-518)

[DAT-518] SAP Service - Filtrar los BPs inactivos cuando se hace un get desde SAP

---

Doppler.Sap.Test/Controllers/BusinessPartnerControllerTest.cs
Doppler.Sap/Controllers/BusinessPartnerController.cs

We add more Slack notification because some problems are not displayed in sap-service-monitor

feat: add slack notification in BP controller

---

Doppler.Sap/appsettings.json

feat: update sap servers

---

Doppler.Sap/Controllers/BillingController.cs
Doppler.Sap/Controllers/BusinessPartnerController.cs
Doppler.Sap/Doppler.Sap.csproj
Doppler.Sap/appsettings.Development.json
Doppler.Sap/appsettings.int.json
Doppler.Sap/appsettings.json
Doppler.Sap/appsettings.qa.json

Add Loggly for all endpoints
Credencials:  https://makingsense.atlassian.net/wiki/spaces/DMDA/pages/818970683/Credenciales

feat: [DAT-563] Add loggly log

---

Doppler.Sap.Test/BillingServiceTest.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs

Add Doppler legend in the free text for the Arg SAP
Task: [DAT-954](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-954)

[DAT-954] - Add Doppler legend in the free text for the Arg SAP

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Mappers/Dictionary.cs
Doppler.Sap/Resources/SapBillingItems.json

Send the invoice or sale order when the user buys SMS credits.
**Task:** [DAT-1344](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1344)
[DAT-1344]: https://makingsense.atlassian.net/browse/DAT-1344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1344] Send invoice u sale order when the user buys SMS credits

---

Doppler.Sap/Controllers/BusinessPartnerController.cs

Remove unnecessary slack alerts.
**Task:** [DAT-574](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-574)
[DAT-574]: https://makingsense.atlassian.net/browse/DAT-574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-574] - Remove unnecessary slack alerts

---

Dockerfile
Doppler.Sap.Test/Doppler.Sap.Test.csproj
Doppler.Sap/Doppler.Sap.csproj
Doppler.Sap/Factory/CreditNoteHandler.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Update dependencies and framework to .NET 7

[DAT-1377] - update dependencies

---

Dockerfile
Doppler.Sap.Test/Doppler.Sap.Test.csproj
Doppler.Sap/Doppler.Sap.csproj

chore: update dependencies

---

Doppler.Sap/Enums/AdditionalServiceTypeEnum.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Models/AdditionalServiceModel.cs
Doppler.Sap/Models/BillingItemPlanDescriptionModel.cs
Doppler.Sap/Models/BillingRequest.cs
Doppler.Sap/Resources/SapBillingItems.json

Support send  to additional services to SAP
**Task:** [DAT-1661](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1661)
[DAT-1661]: https://makingsense.atlassian.net/browse/DAT-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1661] - Support additional services

---

Doppler.Sap/Enums/AdditionalServiceTypeEnum.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Mappers/Dictionary.cs
Doppler.Sap/Models/AdditionalServiceModel.cs
Doppler.Sap/Models/BillingItemPlanDescriptionModel.cs
Doppler.Sap/Models/Pack.cs
Doppler.Sap/Resources/SapBillingItems.json

Support landing plan. Generate the OV or invoice when the user buys a landing's packs and send it to SAP.
**Task:** [DAT-1929](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1929)
[DAT-1929]: https://makingsense.atlassian.net/browse/DAT-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1929] Support landing plan

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Update free text for the landing plans
**Task:**[DAT-1929](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1929)
[DAT-1929]: https://makingsense.atlassian.net/browse/DAT-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-1929] - Update free text for the landing plans

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Models/AdditionalServiceModel.cs

Change obtains discount
**Task:** [DAT-2042](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2042)
[DAT-2042]: https://makingsense.atlassian.net/browse/DAT-2042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2042] Change obtains discount

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Models/AdditionalServiceModel.cs
Doppler.Sap/Resources/SapBillingItems.json

Map new conversation items
**Task:** [DAT-2124](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2124)
[DAT-2124]: https://makingsense.atlassian.net/browse/DAT-2124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2124] - Map new conversation items

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs

[No-task] - Fix issue map ar

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

[no-ticket] fix issue to calculate amount

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Fix issue when show discount for the additional service

[no task] fix issue when show discount for the additional service

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Models/AdditionalServiceModel.cs

Support surplus conversations
**Task:** [DAT-2162](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2162)
[DAT-2162]: https://makingsense.atlassian.net/browse/DAT-2162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2162] Support surplus conversations

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Resources/SapBillingItems.json

Add TaxCode for the surplus conversation line

[DAT-2162] Add TaxCode for the surplus conversation line

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs

Change free text for the conversation plan (SAP AR)

[No-Task] Change free text for the conversation plan

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Models/AdditionalServiceModel.cs

Show correct message with discount

[no-task] Show correct message with discount

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs

Add doppler legend landing for the AR mapper

[no-task] - Add doppler legend landing for the AR mapper

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

fix issue to calculate discount

fix: fix issue to calculate discount

---

Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

[no-task] update free text

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Calculate the amount in the free text

[no-task] - Calculate the amount in the free text

---

Doppler.Sap/Resources/SapBillingItems.json

Add new conversation plans
**Task:** [DAT-2201](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2201)
[DAT-2201]: https://makingsense.atlassian.net/browse/DAT-2201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2201] - Add new conversation plans

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Models/AdditionalServiceModel.cs

Send custom plan to sap
**Task:** [DAT-2209](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2209)
[DAT-2209]: https://makingsense.atlassian.net/browse/DAT-2209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2209] - Send custom plan to sap

---

Doppler.Sap/Resources/SapBillingItems.json

Task: [DAT-2222](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2222)
[DAT-2222]: https://makingsense.atlassian.net/browse/DAT-2222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2222] Add new plan info

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Models/AdditionalServiceModel.cs

Add userid in the freetext when the user is a cm
Task: [DAT-2224](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2224)
[DAT-2224]: https://makingsense.atlassian.net/browse/DAT-2224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2224] - Add userid in the freetext when the user is a cm

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Add user id for the landing plans for the cm users
**Task:** [DAT-2224](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2224)
[DAT-2224]: https://makingsense.atlassian.net/browse/DAT-2224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2224] - Add user id for the landing plans for the cm users

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Models/AdditionalServiceModel.cs

Show email in the free text
**Task:** [DAT-2224](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2224)
[DAT-2224]: https://makingsense.atlassian.net/browse/DAT-2224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2224] - Show email in the free text

---

Doppler.Sap/Enums/AdditionalServiceTypeEnum.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs
Doppler.Sap/Resources/SapBillingItems.json

Add new items for the onsite plans
**Task:** [DAT-2255](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2255)
[DAT-2255]: https://makingsense.atlassian.net/browse/DAT-2255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2255] - Add new items for the onsite plans

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Fix issue when get the document lines

[no-task] - Fix issue when get the document lines

---

Doppler.Sap/Resources/SapBillingItems.json

Add new articles in the SAP
**Task:** [DAT-2285](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2285)
[DAT-2285]: https://makingsense.atlassian.net/browse/DAT-2285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2285] - Add new articles in the SAP

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

[no-task] Rename onsite plan

---

Doppler.Sap/Resources/SapBillingItems.json

Add map for the new plan for the onsite
Task: [DAT-2347](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2347)
[DAT-2347]: https://makingsense.atlassian.net/browse/DAT-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2347] - Add map for the new plan for the onsite

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Change legend for the CM users

[no-task] Change legend for the CM users

---

Doppler.Sap/Enums/AdditionalServiceTypeEnum.cs
Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Models/AdditionalServiceModel.cs
Doppler.Sap/Models/BillingItemPlanDescriptionModel.cs
Doppler.Sap/Resources/SapBillingItems.json

Support send push notification plan
**Task:** [](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2414)

[DAT-2414] - Support send push notification plan

---

Doppler.Sap/Mappers/Billing/BillingForArMapper.cs
Doppler.Sap/Mappers/Billing/BillingForUsMapper.cs

Update legend in the free text
**Task:** [DAT-2414](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2414)
[DAT-2414]: https://makingsense.atlassian.net/browse/DAT-2414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2414] - Update legend in the free text

---

Doppler.Sap/Resources/SapBillingItems.json

Map new items for the push notifications plans
**Task:** [DAT-2467](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2467)
[DAT-2467]: https://makingsense.atlassian.net/browse/DAT-2467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DAT-2467] - Map new items for the push notifications plans
